language: java
# whitelist
branches:
  only:
    - A
    - master
    - dev
addons:
  sonarcloud:
    organization: "deshilearning"
    token:
      secure: d6b7720e60a8462e2a8265ce52ccd75a7e232dd8
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar